// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 ZKPassport

/*
 * DeploySubVerifier.s.sol
 *
 * Deploys the 10 UltraHonk outer-circuit proof verifiers, deploys a SubVerifier (canonical
 * contract imported from the registry-contracts package), wires the proof verifiers + their
 * vkey hashes, optionally sets the default OPRF public key hash, and transfers admin to
 * the final ADMIN_ADDRESS. Does NOT register the SubVerifier with the RootVerifier — that
 * registration is performed by the RootVerifier admin (a Safe multisig) outside this script.
 *
 * The broadcaster is the temporary admin during deployment so it can call admin-only setup
 * functions (addProofVerifiers, setGlobalOPRFPubKeyHash). Admin is transferred to
 * ADMIN_ADDRESS at the end of the script.
 *
 * Required env vars:
 *   PRIVATE_KEY            - deployer key (becomes temporary admin)
 *   ROOT_VERIFIER_ADDRESS  - already-deployed RootVerifier this SubVerifier targets
 *   ADMIN_ADDRESS          - final admin (e.g. multisig) for the new SubVerifier
 *
 * Optional env vars:
 *   SUB_VERIFIER_VERSION      - bytes32 semver key. Recorded in the addresses JSON only.
 *                                Defaults to bytes32(0) (rendered as "unversioned").
 *   GLOBAL_OPRF_PUB_KEY_HASH - protocol-default OPRF pubkey hash. When non-zero, set via
 *                                setGlobalOPRFPubKeyHash. Otherwise admin can set later.
 */

pragma solidity ^0.8.30;

import {console} from "forge-std/Script.sol";
import {DeployBase} from "./DeployBase.s.sol";
import {HonkVerifier as OuterCount4Verifier} from "../src/ultra-honk-verifiers/OuterCount4.sol";
import {HonkVerifier as OuterCount5Verifier} from "../src/ultra-honk-verifiers/OuterCount5.sol";
import {HonkVerifier as OuterCount6Verifier} from "../src/ultra-honk-verifiers/OuterCount6.sol";
import {HonkVerifier as OuterCount7Verifier} from "../src/ultra-honk-verifiers/OuterCount7.sol";
import {HonkVerifier as OuterCount8Verifier} from "../src/ultra-honk-verifiers/OuterCount8.sol";
import {HonkVerifier as OuterCount9Verifier} from "../src/ultra-honk-verifiers/OuterCount9.sol";
import {HonkVerifier as OuterCount10Verifier} from "../src/ultra-honk-verifiers/OuterCount10.sol";
import {HonkVerifier as OuterCount11Verifier} from "../src/ultra-honk-verifiers/OuterCount11.sol";
import {HonkVerifier as OuterCount12Verifier} from "../src/ultra-honk-verifiers/OuterCount12.sol";
import {HonkVerifier as OuterCount13Verifier} from "../src/ultra-honk-verifiers/OuterCount13.sol";
import {RootVerifier} from "@zkpassport/registry-contracts/RootVerifier.sol";
import {SubVerifier} from "@zkpassport/registry-contracts/SubVerifier.sol";
import {ProofVerifier} from "@zkpassport/registry-contracts/lib/Types.sol";

contract DeploySubVerifier is DeployBase {
  bytes32 public SUB_VERIFIER_VERSION;

  // vkey hashes for the 10 outer UltraHonk proof verifiers (outer_count_4 .. outer_count_13).
  // Auto-generated by `src/ts/scripts/circuit-packager.ts` — do not edit by hand.
  bytes32[] public vkeyHashes = [
    // Outer (4 subproofs)
    bytes32(hex"12a8e84286dc51bc37c5424386227f3774c61bed7b391b33d6c6c32709565802"),
    // Outer (5 subproofs)
    bytes32(hex"0550a6f16ed7dcf4d75ee99d9169b9dc7e59638601c97b85a567de91344f66e9"),
    // Outer (6 subproofs)
    bytes32(hex"153f1a4663f7953f51c4f6afd13c70ecf8158948569e0dc550c48cf31989fb85"),
    // Outer (7 subproofs)
    bytes32(hex"2021c2debee20d2d9665a9e7e54b422647c992a17898c5ef19987b7ff6e042e5"),
    // Outer (8 subproofs)
    bytes32(hex"1806e3f9b6075fef3c3b85de5842233c11babd7968ad06416f00c5ec36138216"),
    // Outer (9 subproofs)
    bytes32(hex"143218882fd82ae2bef7ac28dc0de20b98f138a943322a2ac9d25ef99cd77b2a"),
    // Outer (10 subproofs)
    bytes32(hex"1dca01c1282d04c81aae419f719cf3bd430898085545b5ea34469c292510419b"),
    // Outer (11 subproofs)
    bytes32(hex"2640781f7e70c1115e97ba609ff60bd72a998db58e6329ea66b9f2e3abbe7c89"),
    // Outer (12 subproofs)
    bytes32(hex"1d12898452d6ceb59a5a1e67533e750e5fa4aa7b1726796852caac0cc8a09118"),
    // Outer (13 subproofs)
    bytes32(hex"188c47de0d773a50f2ff1005a6e7022f01915374b177ce3cf689cd1e770c55ba")
  ];
  address[] public proofVerifiers = new address[](10);

  function setUp() public {}

  function run() public {
    // Validate env
    SUB_VERIFIER_VERSION = vm.envOr("SUB_VERIFIER_VERSION", bytes32(0));
    address adminAddress = vm.envAddress("ADMIN_ADDRESS");
    require(adminAddress != address(0), "ADMIN_ADDRESS must be set");
    RootVerifier rootVerifier = RootVerifier(vm.envAddress("ROOT_VERIFIER_ADDRESS"));
    require(address(rootVerifier) != address(0), "ROOT_VERIFIER_ADDRESS must be set");
    bytes32 globalOPRFPubKeyHash = vm.envOr("GLOBAL_OPRF_PUB_KEY_HASH", bytes32(0));

    uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
    address deployer = vm.addr(deployerPrivateKey);
    vm.startBroadcast(deployerPrivateKey);

    // Deploy the 10 UltraHonk proof verifiers.
    console.log("Deploying outer proof verifiers...");
    proofVerifiers[0] = address(new OuterCount4Verifier());
    proofVerifiers[1] = address(new OuterCount5Verifier());
    proofVerifiers[2] = address(new OuterCount6Verifier());
    proofVerifiers[3] = address(new OuterCount7Verifier());
    proofVerifiers[4] = address(new OuterCount8Verifier());
    proofVerifiers[5] = address(new OuterCount9Verifier());
    proofVerifiers[6] = address(new OuterCount10Verifier());
    proofVerifiers[7] = address(new OuterCount11Verifier());
    proofVerifiers[8] = address(new OuterCount12Verifier());
    proofVerifiers[9] = address(new OuterCount13Verifier());
    for (uint256 i = 0; i < 10; i++) {
      console.log("  outer_count_", i + 4, "deployed at:", proofVerifiers[i]);
    }

    // Deploy the SubVerifier with the broadcaster as temporary admin.
    console.log("Deploying SubVerifier...");
    SubVerifier subVerifier = new SubVerifier(deployer, rootVerifier, globalOPRFPubKeyHash);
    console.log("SubVerifier deployed at:", address(subVerifier));

    // Wire proof verifiers (admin-only on SubVerifier).
    ProofVerifier[] memory pvArray = new ProofVerifier[](10);
    for (uint256 i = 0; i < 10; i++) {
      pvArray[i] = ProofVerifier({vkeyHash: vkeyHashes[i], verifier: proofVerifiers[i]});
    }
    subVerifier.addProofVerifiers(pvArray);
    console.log("Proof verifiers added");

    // Hand admin over to the final admin (e.g. multisig).
    subVerifier.transferAdmin(adminAddress);
    console.log("Admin transferred to:", adminAddress);

    vm.stopBroadcast();

    _writeAddresses(rootVerifier, subVerifier, adminAddress);

    console.log("");
    console.log("Next: RootVerifier admin (multisig) calls addSubVerifier(version, %s)", address(subVerifier));
  }

  function _writeAddresses(RootVerifier rootVerifier, SubVerifier subVerifier, address adminAddress) internal {
    string memory versionStr = _versionString(SUB_VERIFIER_VERSION);

    // proof_verifiers object keyed by outer_count_N
    string memory pvJson = "pv";
    vm.serializeAddress(pvJson, "outer_count_4", proofVerifiers[0]);
    vm.serializeAddress(pvJson, "outer_count_5", proofVerifiers[1]);
    vm.serializeAddress(pvJson, "outer_count_6", proofVerifiers[2]);
    vm.serializeAddress(pvJson, "outer_count_7", proofVerifiers[3]);
    vm.serializeAddress(pvJson, "outer_count_8", proofVerifiers[4]);
    vm.serializeAddress(pvJson, "outer_count_9", proofVerifiers[5]);
    vm.serializeAddress(pvJson, "outer_count_10", proofVerifiers[6]);
    vm.serializeAddress(pvJson, "outer_count_11", proofVerifiers[7]);
    vm.serializeAddress(pvJson, "outer_count_12", proofVerifiers[8]);
    pvJson = vm.serializeAddress(pvJson, "outer_count_13", proofVerifiers[9]);

    // version object: { address, admin, root_verifier, proof_verifiers, deployed_at }
    string memory versionJson = "subverifier_version";
    vm.serializeAddress(versionJson, "address", address(subVerifier));
    vm.serializeAddress(versionJson, "admin", adminAddress);
    vm.serializeAddress(versionJson, "root_verifier", address(rootVerifier));
    vm.serializeUint(versionJson, "deployed_at", block.timestamp);
    versionJson = vm.serializeString(versionJson, "proof_verifiers", pvJson);

    // sub_verifier_versions: { "<version>": { ... } }
    string memory section = "sub_verifier_versions";
    section = vm.serializeString(section, versionStr, versionJson);

    _writeToAddresses("sub_verifier_versions", section);
  }

  function _versionString(bytes32 version) internal pure returns (string memory) {
    if (version == bytes32(0)) return "unversioned";
    uint256 v = uint256(version);
    return string.concat(
      vm.toString(uint16(v >> 240)), ".", vm.toString(uint16(v >> 224)), ".", vm.toString(uint16(v >> 208))
    );
  }
}
