// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 ZKPassport

/*
 * DeploySubVerifier.s.sol
 *
 * Deploys the 10 UltraHonk outer-circuit proof verifiers, deploys a SubVerifier (canonical
 * contract imported from the registry-contracts package), wires the proof verifiers + their
 * vkey hashes, optionally sets the default OPRF public key hash, and transfers admin to
 * the final ADMIN_ADDRESS. Does NOT register the SubVerifier with the RootVerifier — that
 * registration is performed by the RootVerifier admin (a Safe multisig) outside this script.
 *
 * The broadcaster is the temporary admin during deployment so it can call admin-only setup
 * functions (addProofVerifiers, setGlobalOPRFPubKeyHash). Admin is transferred to
 * ADMIN_ADDRESS at the end of the script.
 *
 * Required env vars:
 *   PRIVATE_KEY            - deployer key (becomes temporary admin)
 *   ROOT_VERIFIER_ADDRESS  - already-deployed RootVerifier this SubVerifier targets
 *   ADMIN_ADDRESS          - final admin (e.g. multisig) for the new SubVerifier
 *
 * Optional env vars:
 *   SUB_VERIFIER_VERSION      - bytes32 semver key. Recorded in the addresses JSON only.
 *                                Defaults to bytes32(0) (rendered as "unversioned").
 *   GLOBAL_OPRF_PUB_KEY_HASH - protocol-default OPRF pubkey hash. When non-zero, set via
 *                                setGlobalOPRFPubKeyHash. Otherwise admin can set later.
 */

pragma solidity ^0.8.30;

import {console} from "forge-std/Script.sol";
import {DeployBase} from "./DeployBase.s.sol";
import {HonkVerifier as OuterCount4Verifier} from "../src/ultra-honk-verifiers/OuterCount4.sol";
import {HonkVerifier as OuterCount5Verifier} from "../src/ultra-honk-verifiers/OuterCount5.sol";
import {HonkVerifier as OuterCount6Verifier} from "../src/ultra-honk-verifiers/OuterCount6.sol";
import {HonkVerifier as OuterCount7Verifier} from "../src/ultra-honk-verifiers/OuterCount7.sol";
import {HonkVerifier as OuterCount8Verifier} from "../src/ultra-honk-verifiers/OuterCount8.sol";
import {HonkVerifier as OuterCount9Verifier} from "../src/ultra-honk-verifiers/OuterCount9.sol";
import {HonkVerifier as OuterCount10Verifier} from "../src/ultra-honk-verifiers/OuterCount10.sol";
import {HonkVerifier as OuterCount11Verifier} from "../src/ultra-honk-verifiers/OuterCount11.sol";
import {HonkVerifier as OuterCount12Verifier} from "../src/ultra-honk-verifiers/OuterCount12.sol";
import {HonkVerifier as OuterCount13Verifier} from "../src/ultra-honk-verifiers/OuterCount13.sol";
import {RootVerifier} from "@zkpassport/registry-contracts/RootVerifier.sol";
import {SubVerifier} from "@zkpassport/registry-contracts/SubVerifier.sol";
import {ProofVerifier} from "@zkpassport/registry-contracts/lib/Types.sol";

contract DeploySubVerifier is DeployBase {
  bytes32 public SUB_VERIFIER_VERSION;

  // vkey hashes for the 10 outer UltraHonk proof verifiers (outer_count_4 .. outer_count_13).
  // Auto-generated by `src/ts/scripts/circuit-packager.ts` — do not edit by hand.
  bytes32[] public vkeyHashes = [
    // Outer (4 subproofs)
    bytes32(hex"032e5c838dd5e2b64826f11777f2b12b03667eb9ca78429ec23acc50c8061d7e"),
    // Outer (5 subproofs)
    bytes32(hex"013d18b35786455360821b6dbcb40174603cac5893781f0fc1601af4eacb01eb"),
    // Outer (6 subproofs)
    bytes32(hex"25de0e8ba3d6b6346c1ef7530adfb51a653f91a330a177ce734b1ec5121074a6"),
    // Outer (7 subproofs)
    bytes32(hex"00fe2b15b91a3c7c3ede7f84a0751e29373bfbf2da0ab7392e2cfa564eab8ab7"),
    // Outer (8 subproofs)
    bytes32(hex"03dbb84b656cdf3b9f93d809c530b4c3901fe5be6f56c424a04ae827ebe45a08"),
    // Outer (9 subproofs)
    bytes32(hex"1546bce87d034c37bb18a681786d4d911bc706c9b99e394475ffb379ce275bb8"),
    // Outer (10 subproofs)
    bytes32(hex"123f66f35744a566cad2891bd0ccac9be700ac01bba930456fbb768979212620"),
    // Outer (11 subproofs)
    bytes32(hex"2f4364659e530b0b7cc7cbe452e2f6fd621ca3def5126d5b3a6d79afd0a0c9f1"),
    // Outer (12 subproofs)
    bytes32(hex"11fea68166b26d2efe63f68d1753574fa217123295044c5ba1cf1f0b6582f5a9"),
    // Outer (13 subproofs)
    bytes32(hex"24f7d5dd3cc19496e5859d401dbdbc99097124e17d7816eb244752b2e94d352e")
  ];
  address[] public proofVerifiers = new address[](10);

  function setUp() public {}

  function run() public {
    // Validate env
    SUB_VERIFIER_VERSION = vm.envOr("SUB_VERIFIER_VERSION", bytes32(0));
    address adminAddress = vm.envAddress("ADMIN_ADDRESS");
    require(adminAddress != address(0), "ADMIN_ADDRESS must be set");
    RootVerifier rootVerifier = RootVerifier(vm.envAddress("ROOT_VERIFIER_ADDRESS"));
    require(address(rootVerifier) != address(0), "ROOT_VERIFIER_ADDRESS must be set");
    bytes32 globalOPRFPubKeyHash = vm.envOr("GLOBAL_OPRF_PUB_KEY_HASH", bytes32(0));

    uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
    address deployer = vm.addr(deployerPrivateKey);
    vm.startBroadcast(deployerPrivateKey);

    // Deploy the 10 UltraHonk proof verifiers.
    console.log("Deploying outer proof verifiers...");
    proofVerifiers[0] = address(new OuterCount4Verifier());
    proofVerifiers[1] = address(new OuterCount5Verifier());
    proofVerifiers[2] = address(new OuterCount6Verifier());
    proofVerifiers[3] = address(new OuterCount7Verifier());
    proofVerifiers[4] = address(new OuterCount8Verifier());
    proofVerifiers[5] = address(new OuterCount9Verifier());
    proofVerifiers[6] = address(new OuterCount10Verifier());
    proofVerifiers[7] = address(new OuterCount11Verifier());
    proofVerifiers[8] = address(new OuterCount12Verifier());
    proofVerifiers[9] = address(new OuterCount13Verifier());
    for (uint256 i = 0; i < 10; i++) {
      console.log("  outer_count_", i + 4, "deployed at:", proofVerifiers[i]);
    }

    // Deploy the SubVerifier with the broadcaster as temporary admin.
    console.log("Deploying SubVerifier...");
    SubVerifier subVerifier = new SubVerifier(deployer, rootVerifier, globalOPRFPubKeyHash);
    console.log("SubVerifier deployed at:", address(subVerifier));

    // Wire proof verifiers (admin-only on SubVerifier).
    ProofVerifier[] memory pvArray = new ProofVerifier[](10);
    for (uint256 i = 0; i < 10; i++) {
      pvArray[i] = ProofVerifier({vkeyHash: vkeyHashes[i], verifier: proofVerifiers[i]});
    }
    subVerifier.addProofVerifiers(pvArray);
    console.log("Proof verifiers added");

    // Hand admin over to the final admin (e.g. multisig).
    subVerifier.transferAdmin(adminAddress);
    console.log("Admin transferred to:", adminAddress);

    vm.stopBroadcast();

    _writeAddresses(rootVerifier, subVerifier, adminAddress);

    console.log("");
    console.log("Next: RootVerifier admin (multisig) calls addSubVerifier(version, %s)", address(subVerifier));
  }

  function _writeAddresses(RootVerifier rootVerifier, SubVerifier subVerifier, address adminAddress) internal {
    string memory versionStr = _versionString(SUB_VERIFIER_VERSION);

    // proof_verifiers object keyed by outer_count_N
    string memory pvJson = "pv";
    vm.serializeAddress(pvJson, "outer_count_4", proofVerifiers[0]);
    vm.serializeAddress(pvJson, "outer_count_5", proofVerifiers[1]);
    vm.serializeAddress(pvJson, "outer_count_6", proofVerifiers[2]);
    vm.serializeAddress(pvJson, "outer_count_7", proofVerifiers[3]);
    vm.serializeAddress(pvJson, "outer_count_8", proofVerifiers[4]);
    vm.serializeAddress(pvJson, "outer_count_9", proofVerifiers[5]);
    vm.serializeAddress(pvJson, "outer_count_10", proofVerifiers[6]);
    vm.serializeAddress(pvJson, "outer_count_11", proofVerifiers[7]);
    vm.serializeAddress(pvJson, "outer_count_12", proofVerifiers[8]);
    pvJson = vm.serializeAddress(pvJson, "outer_count_13", proofVerifiers[9]);

    // version object: { address, admin, root_verifier, proof_verifiers, deployed_at }
    string memory versionJson = "subverifier_version";
    vm.serializeAddress(versionJson, "address", address(subVerifier));
    vm.serializeAddress(versionJson, "admin", adminAddress);
    vm.serializeAddress(versionJson, "root_verifier", address(rootVerifier));
    vm.serializeUint(versionJson, "deployed_at", block.timestamp);
    versionJson = vm.serializeString(versionJson, "proof_verifiers", pvJson);

    // sub_verifier_versions: { "<version>": { ... } }
    string memory section = "sub_verifier_versions";
    section = vm.serializeString(section, versionStr, versionJson);

    _writeToAddresses("sub_verifier_versions", section);
  }

  function _versionString(bytes32 version) internal pure returns (string memory) {
    if (version == bytes32(0)) return "unversioned";
    uint256 v = uint256(version);
    return string.concat(
      vm.toString(uint16(v >> 240)), ".", vm.toString(uint16(v >> 224)), ".", vm.toString(uint16(v >> 208))
    );
  }
}
