// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 ZKPassport

/*
 * DeploySubVerifier.s.sol
 *
 * Deploys the 10 UltraHonk outer-circuit proof verifiers, deploys a SubVerifier (canonical
 * contract imported from the registry-contracts package), wires the proof verifiers + their
 * vkey hashes, optionally sets the default OPRF public key hash, and transfers admin to
 * the final ADMIN_ADDRESS. Does NOT register the SubVerifier with the RootVerifier — that
 * registration is performed by the RootVerifier admin (a Safe multisig) outside this script.
 *
 * The broadcaster is the temporary admin during deployment so it can call admin-only setup
 * functions (addProofVerifiers, setGlobalOPRFPubKeyHash). Admin is transferred to
 * ADMIN_ADDRESS at the end of the script.
 *
 * Required env vars:
 *   PRIVATE_KEY            - deployer key (becomes temporary admin)
 *   ROOT_VERIFIER_ADDRESS  - already-deployed RootVerifier this SubVerifier targets
 *   ADMIN_ADDRESS          - final admin (e.g. multisig) for the new SubVerifier
 *
 * Optional env vars:
 *   SUB_VERIFIER_VERSION      - bytes32 semver key. Recorded in the addresses JSON only.
 *                                Defaults to bytes32(0) (rendered as "unversioned").
 *   GLOBAL_OPRF_PUB_KEY_HASH - protocol-default OPRF pubkey hash. When non-zero, set via
 *                                setGlobalOPRFPubKeyHash. Otherwise admin can set later.
 */

pragma solidity ^0.8.30;

import {console} from "forge-std/Script.sol";
import {DeployBase} from "./DeployBase.s.sol";
import {HonkVerifier as OuterCount4Verifier} from "../src/ultra-honk-verifiers/OuterCount4.sol";
import {HonkVerifier as OuterCount5Verifier} from "../src/ultra-honk-verifiers/OuterCount5.sol";
import {HonkVerifier as OuterCount6Verifier} from "../src/ultra-honk-verifiers/OuterCount6.sol";
import {HonkVerifier as OuterCount7Verifier} from "../src/ultra-honk-verifiers/OuterCount7.sol";
import {HonkVerifier as OuterCount8Verifier} from "../src/ultra-honk-verifiers/OuterCount8.sol";
import {HonkVerifier as OuterCount9Verifier} from "../src/ultra-honk-verifiers/OuterCount9.sol";
import {HonkVerifier as OuterCount10Verifier} from "../src/ultra-honk-verifiers/OuterCount10.sol";
import {HonkVerifier as OuterCount11Verifier} from "../src/ultra-honk-verifiers/OuterCount11.sol";
import {HonkVerifier as OuterCount12Verifier} from "../src/ultra-honk-verifiers/OuterCount12.sol";
import {HonkVerifier as OuterCount13Verifier} from "../src/ultra-honk-verifiers/OuterCount13.sol";
import {RootVerifier} from "@zkpassport/registry-contracts/RootVerifier.sol";
import {SubVerifier} from "@zkpassport/registry-contracts/SubVerifier.sol";
import {ProofVerifier} from "@zkpassport/registry-contracts/lib/Types.sol";

contract DeploySubVerifier is DeployBase {
  bytes32 public SUB_VERIFIER_VERSION;

  // vkey hashes for the 10 outer UltraHonk proof verifiers (outer_count_4 .. outer_count_13).
  // Auto-generated by `src/ts/scripts/circuit-packager.ts` — do not edit by hand.
  bytes32[] public vkeyHashes = [
    // Outer (4 subproofs)
    bytes32(hex"087e799b012b3440e1666f6094eca0cd5e8ad647f42fabebc0290cc11f7230f7"),
    // Outer (5 subproofs)
    bytes32(hex"2db0280427677f605ab03da584627a2c43c5f3e65ef50155cd7ee9740622c041"),
    // Outer (6 subproofs)
    bytes32(hex"07ef17c4f60c89660e32f62d7ea5017f13d56d6b027a4fa3982839cf8df33faf"),
    // Outer (7 subproofs)
    bytes32(hex"1c6c95cf83576d9065e7d897fde2127462d55d57235a5242218396267d844451"),
    // Outer (8 subproofs)
    bytes32(hex"1540139967c034357325a007c85f6335e3b63c02b4da9ee907b4df606f2747fb"),
    // Outer (9 subproofs)
    bytes32(hex"1e82012fde5ee19ddf69c09c9e76efb30ccf3911137b6015640cc80b2309be7d"),
    // Outer (10 subproofs)
    bytes32(hex"1804ae049b8bdae815f15461a7ef71e9eeaa5ae59f0f7ed1631b26bfcff25830"),
    // Outer (11 subproofs)
    bytes32(hex"111cd763d5ce5dfe72161bc403c1a7bcf3bdaed00fac7d1096e81a0835a45580"),
    // Outer (12 subproofs)
    bytes32(hex"1c9d7bdf9d7b6702f3f79f49737322e9f74ffdfd110f1d4ecc559988ebdb738b"),
    // Outer (13 subproofs)
    bytes32(hex"15b289ff955d8bf593c3f7e3a024c1287eb01490267b56627c7c795ff61dea9d")
  ];
  address[] public proofVerifiers = new address[](10);

  function setUp() public {}

  function run() public {
    // Validate env
    SUB_VERIFIER_VERSION = vm.envOr("SUB_VERIFIER_VERSION", bytes32(0));
    address adminAddress = vm.envAddress("ADMIN_ADDRESS");
    require(adminAddress != address(0), "ADMIN_ADDRESS must be set");
    RootVerifier rootVerifier = RootVerifier(vm.envAddress("ROOT_VERIFIER_ADDRESS"));
    require(address(rootVerifier) != address(0), "ROOT_VERIFIER_ADDRESS must be set");
    bytes32 globalOPRFPubKeyHash = vm.envOr("GLOBAL_OPRF_PUB_KEY_HASH", bytes32(0));

    uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
    address deployer = vm.addr(deployerPrivateKey);
    vm.startBroadcast(deployerPrivateKey);

    // Deploy the 10 UltraHonk proof verifiers.
    console.log("Deploying outer proof verifiers...");
    proofVerifiers[0] = address(new OuterCount4Verifier());
    proofVerifiers[1] = address(new OuterCount5Verifier());
    proofVerifiers[2] = address(new OuterCount6Verifier());
    proofVerifiers[3] = address(new OuterCount7Verifier());
    proofVerifiers[4] = address(new OuterCount8Verifier());
    proofVerifiers[5] = address(new OuterCount9Verifier());
    proofVerifiers[6] = address(new OuterCount10Verifier());
    proofVerifiers[7] = address(new OuterCount11Verifier());
    proofVerifiers[8] = address(new OuterCount12Verifier());
    proofVerifiers[9] = address(new OuterCount13Verifier());
    for (uint256 i = 0; i < 10; i++) {
      console.log("  outer_count_", i + 4, "deployed at:", proofVerifiers[i]);
    }

    // Deploy the SubVerifier with the broadcaster as temporary admin.
    console.log("Deploying SubVerifier...");
    SubVerifier subVerifier = new SubVerifier(deployer, rootVerifier, globalOPRFPubKeyHash);
    console.log("SubVerifier deployed at:", address(subVerifier));

    // Wire proof verifiers (admin-only on SubVerifier).
    ProofVerifier[] memory pvArray = new ProofVerifier[](10);
    for (uint256 i = 0; i < 10; i++) {
      pvArray[i] = ProofVerifier({vkeyHash: vkeyHashes[i], verifier: proofVerifiers[i]});
    }
    subVerifier.addProofVerifiers(pvArray);
    console.log("Proof verifiers added");

    // Hand admin over to the final admin (e.g. multisig).
    subVerifier.transferAdmin(adminAddress);
    console.log("Admin transferred to:", adminAddress);

    vm.stopBroadcast();

    _writeAddresses(rootVerifier, subVerifier, adminAddress);

    console.log("");
    console.log("Next: RootVerifier admin (multisig) calls addSubVerifier(version, %s)", address(subVerifier));
  }

  function _writeAddresses(RootVerifier rootVerifier, SubVerifier subVerifier, address adminAddress) internal {
    string memory versionStr = _versionString(SUB_VERIFIER_VERSION);

    // proof_verifiers object keyed by outer_count_N
    string memory pvJson = "pv";
    vm.serializeAddress(pvJson, "outer_count_4", proofVerifiers[0]);
    vm.serializeAddress(pvJson, "outer_count_5", proofVerifiers[1]);
    vm.serializeAddress(pvJson, "outer_count_6", proofVerifiers[2]);
    vm.serializeAddress(pvJson, "outer_count_7", proofVerifiers[3]);
    vm.serializeAddress(pvJson, "outer_count_8", proofVerifiers[4]);
    vm.serializeAddress(pvJson, "outer_count_9", proofVerifiers[5]);
    vm.serializeAddress(pvJson, "outer_count_10", proofVerifiers[6]);
    vm.serializeAddress(pvJson, "outer_count_11", proofVerifiers[7]);
    vm.serializeAddress(pvJson, "outer_count_12", proofVerifiers[8]);
    pvJson = vm.serializeAddress(pvJson, "outer_count_13", proofVerifiers[9]);

    // version object: { address, admin, root_verifier, proof_verifiers, deployed_at }
    string memory versionJson = "subverifier_version";
    vm.serializeAddress(versionJson, "address", address(subVerifier));
    vm.serializeAddress(versionJson, "admin", adminAddress);
    vm.serializeAddress(versionJson, "root_verifier", address(rootVerifier));
    vm.serializeUint(versionJson, "deployed_at", block.timestamp);
    versionJson = vm.serializeString(versionJson, "proof_verifiers", pvJson);

    // sub_verifier_versions: { "<version>": { ... } }
    string memory section = "sub_verifier_versions";
    section = vm.serializeString(section, versionStr, versionJson);

    _writeToAddresses("sub_verifier_versions", section);
  }

  function _versionString(bytes32 version) internal pure returns (string memory) {
    if (version == bytes32(0)) return "unversioned";
    uint256 v = uint256(version);
    return string.concat(
      vm.toString(uint16(v >> 240)), ".", vm.toString(uint16(v >> 224)), ".", vm.toString(uint16(v >> 208))
    );
  }
}
