[package]
name = "compare_citizenship"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
compare_citizenship = { path = "../../../lib/compare/citizenship" }
commitment = { path = "../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../lib/utils" }
