[package]
name = "facematch_ios"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
facematch = { path = "../../../../lib/facematch" }
commitment = { path = "../../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../../lib/utils" }
data_check_expiry = { path = "../../../../lib/data-check/expiry" }
