[package]
name = "outer_count_13"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
common = { path = "../../../../lib/commitment/common" }
outer_lib = { path = "../../../../lib/outer" }
