[package]
name = "face_match_android_rk_rsa_ik_count_3_ik_rsa_4096_sha256_ik_rsa_2048_sha256_ik_rsa_2048_sha256_evm"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
facematch = { path = "../../../../../../../../../lib/facematch" }
sig_check_rsa = { path = "../../../../../../../../../lib/sig-check/rsa" }
sig_check_ecdsa = { path = "../../../../../../../../../lib/sig-check/ecdsa" }
data_check_tbs_pubkey = { path = "../../../../../../../../../lib/data-check/tbs-pubkey" }
commitment = { path = "../../../../../../../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../../../../../../../lib/utils" }
