[package]
name = "data_check_integrity_sha256"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
data_check_integrity = { path = "../../../../lib/data-check/integrity" }
data_check_expiry = { path = "../../../../lib/data-check/expiry" }
commitment = { path = "../../../../lib/commitment/integrity-to-disclosure" }
utils = { path = "../../../../lib/utils" }