[package]
name = "exclusion_check_ofac_evm"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot", "Maddiaa0"]
compiler_version = ">=1.0.0"

[dependencies]
exclusion_check_ofac = { path = "../../../../lib/exclusion-check/ofac" }
commitment = { path = "../../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../../lib/utils" }
