[package]
name = "data_check_integrity_sa_sha224_dg_sha1"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
data_check_integrity = { path = "../../../../../lib/data-check/integrity" }
commitment = { path = "../../../../../lib/commitment/integrity-to-disclosure" }
utils = { path = "../../../../../lib/utils" }
